/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threefour;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author calvin
 */
public class gameFrame extends javax.swing.JFrame {

    UsersData gameData;
    Player curPlayer = null; 
    
    public gameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataButton = new javax.swing.JButton();
        namesList = new java.awt.List();
        avgTimeList = new java.awt.List();
        pNameText = new javax.swing.JTextField();
        addPlayerButton = new javax.swing.JButton();
        allNamesList = new java.awt.List();
        selectText = new javax.swing.JTextField();
        curPlayerButton = new javax.swing.JButton();
        curNameText = new javax.swing.JTextField();
        curPlayerTimeList = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataButton.setText("Generate Data");
        dataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataButtonActionPerformed(evt);
            }
        });

        addPlayerButton.setText("Add Player");
        addPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerButtonActionPerformed(evt);
            }
        });

        allNamesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allNamesListMouseClicked(evt);
            }
        });

        selectText.setEditable(false);

        curPlayerButton.setText("Set Player");
        curPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curPlayerButtonActionPerformed(evt);
            }
        });

        curNameText.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPlayerButton)
                        .addGap(31, 31, 31)
                        .addComponent(pNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(curNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(selectText))
                        .addGap(21, 21, 21)
                        .addComponent(curPlayerButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allNamesList, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namesList, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(avgTimeList, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(curPlayerTimeList, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(curPlayerTimeList, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(avgTimeList, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addComponent(namesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dataButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addPlayerButton))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(selectText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(curPlayerButton))
                            .addGap(18, 18, 18)
                            .addComponent(curNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(allNamesList, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateLists() {
        ArrayList<Player> temp = gameData.sortUsers();
        
        namesList.removeAll();
        avgTimeList.removeAll();
        allNamesList.removeAll();
        curPlayerTimeList.removeAll();
        
        for (Player p : temp) {
            namesList.add(p.getName());
            avgTimeList.add(String.valueOf((double)Math.round(p.getAvg() * 1000) / 1000));
        }
        
        for (String n : gameData.usedNames) {
            allNamesList.add(n);
        }
        
        if (curPlayer != null) {
            for (Double t : curPlayer.sortTimes()) {
                curPlayerTimeList.add(String.valueOf(t));
            }
        }
    }
    private void dataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataButtonActionPerformed
        gameData = new UsersData();
        String[] names = new String[] {"Bob", "Sam", "Jim", "Sammy"};
        
        for (int i = 0; i < 4; i++) {
            ArrayList temp = new  ArrayList();
            
            temp.add(Math.random());
            temp.add(Math.random());
            temp.add(Math.random());
            temp.add(Math.random());
            
            gameData.addUser(names[i], temp);
        }
        
        updateLists();
    }//GEN-LAST:event_dataButtonActionPerformed

    private void addPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerButtonActionPerformed
        String name = pNameText.getText();
        
        boolean addedPlayer = gameData.addUser(name);
        
        if (addedPlayer != true) {
            pNameText.setText("Name already used");
        }
        updateLists();
    }//GEN-LAST:event_addPlayerButtonActionPerformed

    private void allNamesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allNamesListMouseClicked
        String selected = allNamesList.getSelectedItem();
        
        selectText.setText(selected);
    }//GEN-LAST:event_allNamesListMouseClicked

    private void curPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curPlayerButtonActionPerformed
        String name = selectText.getText();
        curPlayer = gameData.setCurrentUser(name);
        
        if (curPlayer == null) 
            selectText.setText("Invalid player selected.");
        else {
            curNameText.setText(curPlayer.getName());
            updateLists();
        }
    }//GEN-LAST:event_curPlayerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayerButton;
    private java.awt.List allNamesList;
    private java.awt.List avgTimeList;
    private javax.swing.JTextField curNameText;
    private javax.swing.JButton curPlayerButton;
    private java.awt.List curPlayerTimeList;
    private javax.swing.JButton dataButton;
    private java.awt.List namesList;
    private javax.swing.JTextField pNameText;
    private javax.swing.JTextField selectText;
    // End of variables declaration//GEN-END:variables
}
