/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threefour;

import java.awt.Choice;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author calvin
 */
public class PlayerSelectionFrame extends javax.swing.JFrame {

    UsersData gameData;
    String p1Name = null;
    String p2Name = null;
    
    JButton setNameButton = new JButton("Set Name");
    JTextField player1Text = new JTextField();;
    JTextField player2Text = new JTextField();;
    Choice names1Choice = new Choice();
    Choice names2Choice = new Choice();
    
    public PlayerSelectionFrame() throws IOException {
        initComponents();
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height;
        int width = screenSize.width;
        this.setSize(400, 400);
        
        String currentDirectory = System.getProperty("user.dir");
        String fullFileName = currentDirectory + "/background.png";

        BufferedImage myImage = ImageIO.read(new File(fullFileName));
        this.setContentPane(new ContentPanel(myImage));
        
        setNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameButtonActionPerformed(evt);
            }
        });
        setNameButton.setBounds(150, 140, 90, 25);
        
        player1Text.setBounds(15, 50, 100, 25);
        player2Text.setBounds(250, 50, 100, 25);
        player2Text.setEnabled(false);
        
        names1Choice.setBounds(120, 58, 20, 15);
        names1Choice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                names1ChoiceItemStateChanged(evt);
            }
        });
        
        names2Choice.setBounds(355, 58, 20, 15);
        names2Choice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                names2ChoiceItemStateChanged(evt);
            }
        });
        names2Choice.setEnabled(false);
        
        
        
        
        this.add(setNameButton);
        this.add(player1Text);
        this.add(player2Text);
        this.add(names1Choice);
        this.add(names2Choice);
        
        // here's the part where i center the jframe on screen
        this.setLocationRelativeTo(null);
        this.setLayout(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namesChoice1 = new java.awt.Choice();
        player1 = new javax.swing.JTextField();
        namesChoice2 = new java.awt.Choice();
        player2 = new javax.swing.JTextField();
        setName = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namesChoice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                namesChoice1ItemStateChanged(evt);
            }
        });

        namesChoice2.setEnabled(false);

        player2.setEnabled(false);

        setName.setText("Set Name");
        setName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namesChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(namesChoice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(setName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namesChoice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namesChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(setName)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setNameButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(p1Name == null) {
            if( ( gameData.addUser(player1Text.getText()) ) || ( gameData.nameSelected(player1Text.getText()) == 1 ) ) {
                p1Name = player1Text.getText();
                gameData.setCurUser(p1Name);
                
                names1Choice.setEnabled(false);
                player1Text.setEnabled(false);
                names2Choice.setEnabled(true);
                player2Text.setEnabled(true);
                
                try {
                    names2Choice.remove(p1Name);
                } catch (Exception e) {
                    
                }
                
            } else {
                player1Text.setText("Invalid name");
            }
        } else if (p2Name == null) { 
            if( ( gameData.addUser(player2Text.getText()) ) || ( gameData.nameSelected(player2Text.getText()) == 1) ) {
                p2Name = player2Text.getText();
                gameData.setCurUser(p2Name);

                names2Choice.setEnabled(false);
                player2Text.setEnabled(false);
                
                setNameButton.setText("Continue");
            } else {
                player2Text.setText("Invalid name");
            }
        } else {
            //CONTINUE TO GAME ROOM
        }
    }
    
    private void setNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameActionPerformed
        if(p1Name == null) {
            if( ( gameData.addUser(player1.getText()) ) || ( gameData.nameSelected(player1.getText()) == 1 ) ) {
                p1Name = player1.getText();
                gameData.setCurUser(p1Name);
                
                namesChoice1.setEnabled(false);
                player1.setEnabled(false);
                namesChoice2.setEnabled(true);
                player2.setEnabled(true);
                
                namesChoice2.remove(p1Name);
            } else {
                player1.setText("Invalid name");
            }
        } else if (p2Name == null) { 
            if( ( gameData.addUser(player2.getText()) ) || ( gameData.nameSelected(player1.getText()) == 1 ) ) {
                p2Name = player2.getText();
                gameData.setCurUser(p2Name);

                namesChoice2.setEnabled(false);
                player2.setEnabled(false);
                
                setName.setText("Continue");
            } else {
                player2.setText("Invalid name");
            }
        } else {
            System.out.println("RUNNING");
            gameData.exportData();
        }
    }//GEN-LAST:event_setNameActionPerformed
    
    private void names1ChoiceItemStateChanged(java.awt.event.ItemEvent evt) {                                              
        player1Text.setText(names1Choice.getSelectedItem());
    } 
    
    private void names2ChoiceItemStateChanged(java.awt.event.ItemEvent evt) {                                              
        player2Text.setText(names2Choice.getSelectedItem());
    }
    
    private void namesChoice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_namesChoice1ItemStateChanged
        player1.setText(namesChoice1.getSelectedItem());
    }//GEN-LAST:event_namesChoice1ItemStateChanged

    public void updateLists() {
        for(String name : gameData.storedNames) {
            names1Choice.add(name);
            names2Choice.add(name);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerSelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PlayerSelectionFrame();
                } catch (IOException ex) {
                    Logger.getLogger(MainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice namesChoice1;
    private java.awt.Choice namesChoice2;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JButton setName;
    // End of variables declaration//GEN-END:variables
}
