package threefour;

import java.util.Arrays;
import motej.Mote;

public class wiimoteTesting extends javax.swing.JFrame {

	static Wiimote[] wiimotes = new Wiimote[2];
	static WiimoteFinder[] wmFinder = new WiimoteFinder[2];
		
	boolean[] ledOff = {false, false, false, false};

	/**
	 * Creates new form wiimoteTesting
	 */
	public wiimoteTesting() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                disconnectButton = new javax.swing.JButton();
                discoverButton = new javax.swing.JToggleButton();
                input1button = new javax.swing.JToggleButton();
                axesLabel = new javax.swing.JLabel();
                buttonLabel = new javax.swing.JLabel();
                discoverButton2 = new javax.swing.JToggleButton();
                input2Button = new javax.swing.JToggleButton();
                printMotesButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                disconnectButton.setText("Disconnect");
                disconnectButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                disconnectButtonActionPerformed(evt);
                        }
                });

                discoverButton.setText("Toggle Discovery");
                discoverButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                discoverButtonActionPerformed(evt);
                        }
                });

                input1button.setText("Player 1 Input");
                input1button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                input1buttonActionPerformed(evt);
                        }
                });

                axesLabel.setText("0,0,0");

                buttonLabel.setText("none");

                discoverButton2.setText("Toggle Discovery 2");
                discoverButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                discoverButton2ActionPerformed(evt);
                        }
                });

                input2Button.setText("Player 2 Input");
                input2Button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                input2ButtonActionPerformed(evt);
                        }
                });

                printMotesButton.setText("Print motes");
                printMotesButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                printMotesButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(discoverButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(discoverButton2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(input1button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(input2Button))
                                        .addComponent(axesLabel)
                                        .addComponent(buttonLabel)
                                        .addComponent(disconnectButton)
                                        .addComponent(printMotesButton))
                                .addContainerGap(130, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(discoverButton)
                                        .addComponent(discoverButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disconnectButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(input1button)
                                        .addComponent(input2Button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(axesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonLabel)
                                .addGap(18, 18, 18)
                                .addComponent(printMotesButton)
                                .addContainerGap(109, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void discoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoverButtonActionPerformed
		addWiimote(0);
        }//GEN-LAST:event_discoverButtonActionPerformed

        private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
		for (int k = 0; k < wiimotes.length; k++) {
			Wiimote wm = wiimotes[k];
			Mote m = wm.getMote();
			m.setPlayerLeds(ledOff);
			m.disconnect();
		}
        }//GEN-LAST:event_disconnectButtonActionPerformed

        private void input1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1buttonActionPerformed
		displayInput(input1button, 0);
        }//GEN-LAST:event_input1buttonActionPerformed

        private void discoverButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoverButton2ActionPerformed
		addWiimote(1);
        }//GEN-LAST:event_discoverButton2ActionPerformed

        private void input2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input2ButtonActionPerformed
		displayInput(input2Button, 1);
        }//GEN-LAST:event_input2ButtonActionPerformed

        private void printMotesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printMotesButtonActionPerformed
		System.out.println(Arrays.toString(wiimotes));
        }//GEN-LAST:event_printMotesButtonActionPerformed

	public void displayInput(javax.swing.JToggleButton togglebutton, int slot) {
		if (togglebutton.isSelected()) {
			Wiimote wm = wiimotes[slot];
			int[] axes = wm.getMotion();
			String button = wm.getButton();
			axesLabel.setText(axes[0] + "," + axes[1] + "," + axes[2]);
			buttonLabel.setText(button);
		}
		else {
			//TODO: stop reading
		}
	}

	public void addWiimote(int slot) {
		wmFinder[slot] = new WiimoteFinder();
		Mote m = wmFinder[slot].findMote();

		boolean[] playerLeds = ledOff;
		playerLeds[slot] = true;
		m.setPlayerLeds(playerLeds);
		m.rumble(2000l);

		Wiimote wm = new Wiimote(m);
		wiimotes[slot] = wm;
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set GTK theme */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("GTK+".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(wiimoteTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(wiimoteTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(wiimoteTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(wiimoteTesting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new wiimoteTesting().setVisible(true);
			}
		});

	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel axesLabel;
        private javax.swing.JLabel buttonLabel;
        private javax.swing.JButton disconnectButton;
        private javax.swing.JToggleButton discoverButton;
        private javax.swing.JToggleButton discoverButton2;
        private javax.swing.JToggleButton input1button;
        private javax.swing.JToggleButton input2Button;
        private javax.swing.JButton printMotesButton;
        // End of variables declaration//GEN-END:variables
}
